# Generated by Django 5.0.8 on 2024-08-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Школа'),
        ),
    ]
