# Generated by Django 5.0.6 on 2024-07-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_olimpiad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softskilltest',
            name='softSkill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.softskill', verbose_name='Навык'),
        ),
    ]
