# Generated by Django 5.0.6 on 2024-07-01 08:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_softskilltest_softskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='additional_text',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='softskilltest',
            name='softSkill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.softskill', verbose_name='Навык'),
        ),
    ]
